version: '3.1'

services:
  app:
    build: .
    image: phoenix
    ports:
      - 4000:4000
      - 5000:5000
    volumes:
      - .:/code
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecret
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
